


#consumidorMC: creaMC eliminaMC productorMC consumidorMC.c
#	gcc -g -W -Wall -pthread consumidorMC -o consumidorMC

productorMC: creaMC eliminaMC productorMC.c
	gcc -g -W -Wall -pthread productorMC.c -o productorMC

creaMC: creaMC.c
	gcc -g -W -Wall -pthread creaMC.c -o creaMC

eliminaMC: eliminaMC.c
	gcc -g -W -Wall -pthread eliminaMC.c -o eliminaMC

